# -*- coding: utf-8 -*-
"""Machine Translation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyU6-1BdiaDWdpc4FY-eey7N0sw8TCVy

# Sequence Modelling
### Natural Language Processing

### Simple RNN() --> Recurrent Neural Network
### Embedding
### LSTM() --> Long Short Term Memory
### GRU() --> Gated Recurrent Unit
### Bidirectional()

# Machine Translation
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import model_selection
import tqdm
import re # Regular Expression

!mkdir ~/.kaggle
! cp kaggle.json ~/ .kaggle
! chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets list

!rm -rf ~/.kaggle
!mkdir ~/.kaggle

!mv kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets list

!ls

!kaggle datasets download -d lonnieqin/englishspanish-translation-dataset

! unzip /content/englishspanish-translation-dataset.zip

data_df = pd.read_csv("/content/data.csv")
data_df

def clean_df(text):
  text = text.lower()
  text = re.sub(r'([^\s\w]|_)+', '', text)
  text = re.sub(r'\d+', '', text)
  text = text.strip()
  text = re.sub(r'\s+', ' ', text)
  text = re.sub(r"won't", "will not", text)
  text = re.sub(r"can\'t", "can not", text)
  text = re.sub(r"n\'t", " not", text)
  text = re.sub(r"\'re", " are", text)
  text = re.sub(r"\'s", " is", text)
  return text


data_df["english"] = data_df["english"].map(clean_df)
data_df["spanish"] = data_df["spanish"].map(clean_df)

data_df

def start_text_end(text):
  text = f"<start> {text} <end>"
  return text


data_df["english"] = data_df["english"].map(start_text_end)
data_df["spanish"] = data_df["spanish"].map(start_text_end)

data_df

def tokenizer(language):
  lang_tokenizer = tf.keras.preprocessing.text.Tokenizer(filters = "!#$%&()*+,-./:;=?@[\\]^_`{|}~\t\n", # This filters is the same as the function we created above
                                                         oov_token = "<OOV>")
  lang_tokenizer.fit_on_texts(language)
  tensor =lang_tokenizer.texts_to_sequences(language)
  tensor = tf.keras.preprocessing.sequence.pad_sequences(tensor, padding = "post")
  return tensor, lang_tokenizer

eng_sequence, eng_tokenize = tokenizer(data_df.english)
spn_sequnece, spn_tokenize = tokenizer(data_df.spanish)

